type: puppeteer
name: puppeteer_papras_7dof

teleop_dt: 0.02
output_type: joint_pos # 'joint_pos' or 'delta_eef_pose'

# for eef-based mapping
motion_mapping: direct_scaling # 'direct_scaling', 'follower_reprojection', 'leader_sreprojection'
motion_scale: 1.0

limb_joint_names:
  robot1: ['robot1/joint1', 'robot1/joint2', 'robot1/joint3', 'robot1/joint4', 'robot1/joint5', 'robot1/joint6','robot1/joint7']

end_effector_link:
  robot1: 'robot1/end_effector_link'

hand_joint_names:
  robot1: ['robot1/gripper']

named_poses:
  #TODO: maybe read this info from srdf file, but conditionally. If not found, use this info
  init: [0.0, -1.057, 0.0, 0.485, 0.0, 1.125, 0.0, 0.0]

# leader limb -> follower limb
direct_mapping: # default is empty, which means 1:1 mapping
  robot1: 'robot1'

asset_cfg:
  asset_dir: 'models/'
  urdf_path: 'models/leaders/papras_7dof_leader.urdf'
  xml_path: 'models/leaders/papras_7dof_leader.xml'

direct_mapping_available_robots: ['papras_7dof']

render_base: 'trimesh'
viewer_args:
    trimesh:
      pq: [-0.84400246, -0.74844073,  0.63149086,  0.79797548,  0.49961321, -0.17853849, -0.28591218]