type: puppeteer
name: puppeteer_ur5

teleop_dt: 0.02
output_type: joint_pos # 'joint_pos' or 'delta_eef_pose'

# for eef-based mapping
motion_mapping: direct_scaling
motion_scale: 1.0

# for ROS-based controller
leader_subscribe_topic: '/leaders/joint_states'
limb_joint_names:
  robot1: ['robot1/joint1', 'robot1/joint2', 'robot1/joint3', 'robot1/joint4', 'robot1/joint5', 'robot1/joint6']

end_effector_link:
  robot1: 'robot1/end_effector_link'

hand_joint_names:
  robot1: ['robot1/gripper']

init_qpos: [0.0, 0.46, 1.55, 2.55, -3, -1.7, 0.0]

# leader limb -> follower limb
direct_mapping: # default is empty, which means 1:1 mapping
  robot1: 'robot1'

reset_pose: [[0.151, 0.288, 0.420]]
reset_cube: [0.200, 0.100, 0.050]

asset_cfg:
  asset_dir: 'models/'
  urdf_path: 'models/leaders/ur5_leader.urdf'
  xml_path: 'models/leaders/ur5_leader.urdf'

direct_mapping_available_robots: ['ur5']
hand_limits: # for gripper range mapping
  robot1: [[-0.35, 0.57]]

render_base: 'trimesh'
viewer_args:
    trimesh:
      pq: [1.51597506, 1.04149913, 0.88220541, 0.34222756, 0.24566453, 0.50989899, 0.75002151]
