mesh_dir: 'models/' # Default directory for meshes
robot_cfg:
  name: g1
  asset_cfg:
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/humanoids/unitree_g1/g1_29dof.urdf' # Path to the URDF file
    xml_path: 'models/humanoids/unitree_g1/g1_29dof.xml' # If you have xml file, specify the path here or just use urdf file here as well
  ignore_collision_pairs: [] # List of collision pairs to ignore, use * for partial match
  teleop_dt: 0.02
  control_dt: 0.002 # Control loop frequency - 125Hz for PAPRAS
  eef_type: null # Type of end effector: 'hand', 'power_gripper', 'parallel_gripper'
  num_eefs: 4 # number of limbs (end effectors) - 1 for single arm, 2 for dual arm...
  limb_joint_names:
    left_leg:
      - 'left_hip_pitch_joint'
      - 'left_hip_roll_joint'
      - 'left_hip_yaw_joint'
      - 'left_knee_joint'
#      - 'left_ankle_pitch_joint'
#      - 'left_ankle_roll_joint'
    right_leg:
      - 'right_hip_pitch_joint'
      - 'right_hip_roll_joint'
      - 'right_hip_yaw_joint'
      - 'right_knee_joint'
#      - 'right_ankle_pitch_joint'
#      - 'right_ankle_roll_joint'
    left_arm:
      - 'left_shoulder_pitch_joint'
      - 'left_shoulder_roll_joint'
      - 'left_shoulder_yaw_joint'
      - 'left_elbow_joint'
      - 'left_wrist_roll_joint'
      - 'left_wrist_pitch_joint'
      - 'left_wrist_yaw_joint'
    right_arm:
      - 'right_shoulder_pitch_joint'
      - 'right_shoulder_roll_joint'
      - 'right_shoulder_yaw_joint'
      - 'right_elbow_joint'
      - 'right_wrist_roll_joint'
      - 'right_wrist_pitch_joint'
      - 'right_wrist_yaw_joint'
  hand_joint_names:  # No hand for this robot
    left_leg: []
    right_leg: []
    left_arm: []
    right_arm: []
  max_joint_vel: 20.0 # Maximum joint velocity
  world_link: 'pelvis'
  end_effector_link:
    left_leg: left_ankle_roll_link
    right_leg: right_ankle_roll_link
    left_arm: left_rubber_hand
    right_arm: right_rubber_hand
  named_poses:
    #TODO: maybe read this info from srdf file, but conditionally. If not found, use this info
    init: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
  viewer_args:
    mujoco:
      azimuth: 172.7000000000001
      distance: 2.6093796441399872
      elevation: -28.550000000000004
      lookat: [-0.21228273,  0.03259374, -0.11615278]
    sapien:
      width: 1510
      height: 768
      fovy: 1.57
      near: 0.1
      far: 100
      pose:
        pos: [ -0.94558, -0.128266, 1.77682 ]
        quat: [ 0.937644, -0.000868946, 0.347589, 0.0023438 ]
    isaacgym:
      cam_pos: [1.41, -0.36, 0.58]
      cam_target: [0.45, -0.23, 0.31]
ik_cfg: # information for inverse kinematics. Use single limb model for each limb.
  # the number of arms in the urdf file, the name of the robot does not matter, but order matters.
  left_leg:
    # chain of joint names from base to end effector
    joint_names: ['left_hip_pitch_joint', 'left_hip_roll_joint', 'left_hip_yaw_joint', 'left_knee_joint']
    ee_link: left_ankle_roll_link
    dt: 0.05
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/humanoids/unitree_g1/g1_29dof.urdf'
    ik_damping: 0.1
    eps: 1e-3
    base_link: left_hip_pitch_link # base_link in the original urdf file,not the base_link in the ik model

  right_leg:
    joint_names: ['right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_knee_joint']
    ee_link: right_ankle_roll_link
    dt: 0.05
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/humanoids/unitree_g1/g1_29dof.urdf'
    ik_damping: 0.1
    eps: 1e-3
    base_link: right_hip_pitch_link # base_link in the original urdf file,not the base_link in the ik model

  left_arm:
    # chain of joint names from base to end effector
    joint_names: ['left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint', 'left_wrist_roll_joint','left_wrist_pitch_joint', 'left_wrist_yaw_joint']
    ee_link: left_rubber_hand
    dt: 0.05
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/humanoids/unitree_g1/g1_29dof.urdf'
    ik_damping: 0.1
    eps: 1e-3
    base_link: left_shoulder_pitch_link # base_link in the original urdf file,not the base_link in the ik model

  right_arm:
    # chain of joint names from base to end effector
    joint_names: ['right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint', 'right_wrist_roll_joint','right_wrist_pitch_joint', 'right_wrist_yaw_joint']
    ee_link: right_rubber_hand
    dt: 0.05
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/humanoids/unitree_g1/g1_29dof.urdf'
    ik_damping: 0.1
    eps: 1e-3
    base_link: right_shoulder_pitch_link # base_link in the original urdf file,not the base_link in the ik model