mesh_dir: 'models/' # Default directory for meshes
robot_cfg:
  name: papras_orthrus
  asset_cfg:
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/PAPRAS/papras_orthrus/papras_orthrus_7dof.urdf' # Path to the URDF file
    xml_path: 'models/PAPRAS/papras_orthrus/papras_orthrus_7dof.xml' # If you have xml file, specify the path here or just use urdf file here as well
  ignore_collision_pairs: []
  control_dt: 0.02 # Control loop frequency - if we are using joint trajectory controller, it is enough
  eef_type: 'parallel_gripper' # Type of end effector: 'hand', 'power_gripper', 'parallel_gripper'
  limb_joint_names:
    robot3: ['robot3/joint1', 'robot3/joint2', 'robot3/joint3', 'robot3/joint4', 'robot3/joint5', 'robot3/joint6','robot3/joint7']
    robot4: ['robot4/joint1', 'robot4/joint2', 'robot4/joint3', 'robot4/joint4', 'robot4/joint5', 'robot4/joint6','robot4/joint7']
  hand_joint_names: # hand names
    robot3: ['robot3/gripper']
    robot4: ['robot4/gripper']
  max_joint_vel: 2.0 # Maximum joint velocity
  end_effector_link:
    robot3: 'robot3/end_effector_link'
    robot4: 'robot4/end_effector_link'

  init_qpos: [-1.48353,  -0.802851, 0.0, 0.261799, -0.15708, 0.5585, 0.925025, 0.0,
             1.48353,  -0.802851, 0.0, 0.261799, 0.15708, 0.5585, -0.925025, 0.0]
  viewer_args:
    mujoco:
      azimuth: 172.7000000000001
      distance: 2.6093796441399872
      elevation: -28.550000000000004
      lookat: [-0.21228273,  0.03259374, -0.11615278]
    sapien:
      width: 1510
      height: 768
      fovy: 1.57
      near: 0.1
      far: 100
      pose:
        pos: [ -0.94558, -0.128266, 1.77682 ]
        quat: [ 0.937644, -0.000868946, 0.347589, 0.0023438 ]
    isaacgym:
      cam_pos: [1.41, -0.36, 0.58]
      cam_target: [0.45, -0.23, 0.31]
    trimesh:
      pq: [2.14341194, 0.28739312, 1.00190149, 0.56870797, 0.33305482, 0.38138592, 0.64822103]

ik_cfg: # information for inverse kinematics. Use single arm model for each arm.
  # the number of arms in the urdf file, the name of the robot does not matter, but order matters.
  robot3:
    # chain of joint names from base to end effector in ik_model
    joint_names: ['robot1/joint1', 'robot1/joint2', 'robot1/joint3', 'robot1/joint4', 'robot1/joint5', 'robot1/joint6', 'robot1/joint7']
    ee_link: robot1/end_effector_link
    dt: 0.05
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/PAPRAS/papras_7dof/papras_7dof.urdf'
    ik_damping: 0.075
    eps: 1e-3
    base_link: robot3/link1 # base_link in the original urdf file,not the base_link in the ik model

  robot4:
    joint_names: ['robot1/joint1', 'robot1/joint2', 'robot1/joint3', 'robot1/joint4', 'robot1/joint5', 'robot1/joint6', 'robot1/joint7']
    ee_link: robot1/end_effector_link
    dt: 0.05
    asset_dir: ${mesh_dir} # Directory for assets
    urdf_path: 'models/PAPRAS/papras_7dof/papras_7dof.urdf'
    ik_damping: 0.075
    eps: 1e-3
    base_link: robot4/link1 # base_link in the original urdf file,not the base_link in the ik model

ros2_cfg:
  lp_filter_alpha: 0.9
  motion_planning: 'interpolate' # moveit or interpolation
  moveit:
    namespace: 'followers'
    arm_group_name: 'arm34'
    hand_group_name: 'gripper34'
    num_planning_attempts: 30
    planning_time: 20.0
    max_velocity_scaling_factor: 0.1
    max_acceleration_scaling_factor: 0.1
    use_move_group_action: True
  state_sub_topic: '/joint_states' # Topic to subscribe for joint states
  state_sub_msg_type: 'sensor_msgs/msg/JointState' # Message type for joint states
  robots:
    robot3:
      arm_control_topic: '/arm3_controller/joint_trajectory'
      arm_control_msg_type: 'JointTrajectory'
      hand_control_topic: '/gripper3_controller/joint_trajectory'
      hand_control_msg_type: 'JointTrajectory'
      arm_state_sub_topic: ${...state_sub_topic}
      hand_state_sub_topic: ${...state_sub_topic}
      arm_state_sub_msg_type: ${...state_sub_msg_type}
      hand_state_sub_msg_type: ${...state_sub_msg_type}
    robot4:
      arm_control_topic: '/arm4_controller/joint_trajectory'
      arm_control_msg_type: 'JointTrajectory'
      hand_control_topic: '/gripper4_controller/joint_trajectory'
      hand_control_msg_type: 'JointTrajectory'
      arm_state_sub_topic: ${...state_sub_topic}
      hand_state_sub_topic: ${...state_sub_topic}
      arm_state_sub_msg_type: ${...state_sub_msg_type}
      hand_state_sub_msg_type: ${...state_sub_msg_type}
  cameras: []
